# Generated by Django 5.1.4 on 2025-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RI", models.FloatField()),
                ("Na", models.FloatField()),
                ("Mg", models.FloatField()),
                ("Al", models.FloatField()),
                ("Si", models.FloatField()),
                ("K", models.FloatField()),
                ("Ca", models.FloatField()),
                ("Ba", models.FloatField()),
                ("Fe", models.FloatField()),
                ("classification", models.CharField(max_length=30)),
            ],
        ),
    ]
