# Generated by Django 5.1.4 on 2025-11-26 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="predresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "予測結果",
                "verbose_name_plural": "予測結果一覧",
            },
        ),
        migrations.AddField(
            model_name="predresult",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="予測日時"
            ),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Al",
            field=models.FloatField(verbose_name="アルミニウム (Al)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Ba",
            field=models.FloatField(verbose_name="バリウム (Ba)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Ca",
            field=models.FloatField(verbose_name="カルシウム (Ca)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Fe",
            field=models.FloatField(verbose_name="鉄 (Fe)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="K",
            field=models.FloatField(verbose_name="カリウム (K)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Mg",
            field=models.FloatField(verbose_name="マグネシウム (Mg)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Na",
            field=models.FloatField(verbose_name="ナトリウム (Na)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="RI",
            field=models.FloatField(verbose_name="屈折率 (RI)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="Si",
            field=models.FloatField(verbose_name="ケイ素 (Si)"),
        ),
        migrations.AlterField(
            model_name="predresult",
            name="classification",
            field=models.CharField(max_length=30, verbose_name="予測分類結果"),
        ),
    ]
